// <auto-generated />
using System;
using CNAB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CNAB.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("CNAB.Models.Entity.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Agencia");

                    b.Property<string>("AgenciaDigito");

                    b.Property<int>("Ativado");

                    b.Property<string>("BancoCodigo");

                    b.Property<string>("ContaCorrente");

                    b.Property<string>("ContaCorrenteDigito");

                    b.Property<DateTime>("DataPagamento");

                    b.Property<string>("EnderecoBairro");

                    b.Property<string>("EnderecoCep");

                    b.Property<string>("EnderecoCidade");

                    b.Property<string>("EnderecoComplemento");

                    b.Property<string>("EnderecoLogradouro");

                    b.Property<string>("EnderecoNumero");

                    b.Property<string>("EnderecoSiglaEstado");

                    b.Property<string>("Inscricao");

                    b.Property<string>("Nome");

                    b.Property<string>("TipoInscricao");

                    b.Property<string>("TipoServico");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agencia = "1",
                            AgenciaDigito = "9",
                            Ativado = 1,
                            BancoCodigo = "77",
                            ContaCorrente = "999999",
                            ContaCorrenteDigito = "9",
                            DataPagamento = new DateTime(2020, 5, 26, 20, 52, 3, 982, DateTimeKind.Local).AddTicks(8727),
                            EnderecoBairro = "CENTRO",
                            EnderecoCep = "31275000",
                            EnderecoCidade = "BELO HORIZONTE",
                            EnderecoComplemento = "SALA 9",
                            EnderecoLogradouro = "AVENIDA PRINCIPAL",
                            EnderecoNumero = "99",
                            EnderecoSiglaEstado = "MG",
                            Inscricao = "999.999.999-99",
                            Nome = "JOAO SILVA",
                            TipoInscricao = "1",
                            Valor = 1000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
